# Generated by Django 4.2 on 2025-04-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0002_medicine_image_medicine_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
    ]
