# Generated by Django 4.2 on 2025-04-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0003_remove_medicine_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
