# Generated by Django 4.2 on 2025-04-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0008_alter_doctor_latitude_alter_doctor_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmetic',
            name='link',
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
