# Generated by Django 4.2 on 2025-05-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0009_remove_cosmetic_link_cosmetic_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bill',
        ),
    ]
