# Generated by Django 4.2 on 2025-05-06 07:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0010_remove_order_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default=datetime.datetime(2025, 5, 6, 7, 46, 43, 504920, tzinfo=datetime.timezone.utc), max_length=15),
            preserve_default=False,
        ),
    ]
