# Generated by Django 4.2 on 2025-05-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0011_order_customer_address_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cosmetic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.cosmetic'),
            preserve_default=False,
        ),
    ]
