# Generated by Django 4.2 on 2025-05-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0012_order_cosmetic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cosmetic',
        ),
    ]
