# Generated by Django 5.2.1 on 2025-07-29 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pharmacy", "0016_remove_order_cancel_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nestle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("batch_no", models.CharField(blank=True, max_length=50, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="nestle_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Pharmacy.admin",
                    ),
                ),
            ],
        ),
    ]
